<?xml version="1.0" encoding="utf-8"?><Database Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=smsgastosdb;User ID=sa" SettingsObjectName="MerrequinhaAPI.Properties.Settings" SettingsPropertyName="smsgastosdbConnectionString" Provider="System.Data.SqlClient" />
</Database>